POST http://localhost/Prodeo/server/CreateProject.php HTTP/1.1
Content-Type: application/json

{
    "ProjectName"           : "Project2",
    "ProjectType"           : "Software",
    "ProjectDescription"    : "A second testing project to test the API for the Test User",
    "User"                  : "Test"
}   